name:                ted
version:             0.1.0.0
github:              "alexgrejuc/ted"
license:             BSD3
author:              "Alex Grejuc"
maintainer:          "grejuca@oregonstate.edu"
copyright:           "Alex Grejuc"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Static Analysis

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexgrejuc/ted#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ted-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ted

tests:
  ted-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ted
